### ISSUE TITLE
NS_LOG and file ending

### ISSUE THREAD

**Issue by TommyPec** [JudeNiroshan/ns-3-dev-git#13]
5) src/trust-routing/model/trust-manager.cc and also trust-entry.cc needs cleanup (NS_LOG_FUNCTION missing, and there are various non-Linux Ctrl-M characters in the file)

**Comment by JudeNiroshan** [comment]
removed the unnecessary NS_LOG statements as they are not meaningful in those places.
https://github.com/JudeNiroshan/ns-3-dev-git/commit/65e843a88ec55b0b08d6c4dc2e0f330da99f89db
