### ISSUE TITLE
Complete aodv-trust-manager

### ISSUE THREAD

**Issue by TommyPec** [JudeNiroshan/ns-3-dev-git#14]
The main thing, however, is that simple-aodv-trust-manager.cc is not close to being complete, tested, or documented.

double SimpleAodvTrustManager::calculateTrust (Address address)
{
  double trustDouble = m_aodvTrustEntry.GetReply () / m_aodvTrustEntry.GetRreq () * 1.0;
}

I would like for you to write down, please, exactly what this class will do, into the Doxygen:

/**
 * \ingroup trust
 * \brief The aodv specific trust operations handler
 */
class SimpleAodvTrustManager : public TrustManager

and I would like you to list out exactly how you plan to test the implementation, before Monday please.

I would like for you to write down, please, exactly what this class will do, into the Doxygen.  Here is a start for you to complete:

/**
 * \ingroup trust
 * \brief The aodv specific trust operations handler
 * This trust manager calculates a trust value for each known node in the network
 * based on the ratio of observed RREP to observed RREQ sent by that node (a ratio between
 * 0 and 1).  The trust value is then used to select the route, as follows [JUDE TO DESCRIBE]
*/
class SimpleAodvTrustManager : public TrustManager

and then please add the class declaration and the method's doxygen for whatever is still missing from this class.

**Comment by JudeNiroshan** [comment]
https://github.com/JudeNiroshan/ns-3-dev-git/commit/1dc899a578d8060b03aff4dc8bf45254067846fc

Please let me know if I need to add more stuff
