### ISSUE TITLE
internet module changes

### ISSUE THREAD

**Issue by tomhenderson** [JudeNiroshan/ns-3-dev-git#7]
-- a/src/internet/helper/ipv4-routing-helper.cc
+++ b/src/internet/helper/ipv4-routing-helper.cc
@@ -35,6 +35,10 @@ Ipv4RoutingHelper::~Ipv4RoutingHelper ()
 {
 }
 
+Ipv4RoutingHelper::Ipv4RoutingHelper ()
+{
+}
+
 void
 Ipv4RoutingHelper::PrintRoutingTableAllAt (Time printTime, Ptr<OutputStreamWrapper> stream, Time::Unit unit)
 {
@@ -187,4 +191,13 @@ Ipv4RoutingHelper::PrintArpCacheEvery (Time printInterval, Ptr<Node> node, Ptr<O
     }
 }
 
+void Ipv4RoutingHelper::SetEnableTrust (bool enableTrust)
+{
+  this->enableTrust = enableTrust;
+}
+
+bool Ipv4RoutingHelper::IsEnableTrust ()
+{
+  return this->enableTrust;
+}
 } // namespace ns3

I believe that these changes should be removed (in the cc and h files).  No changes to internet module if I do a 'git diff origin/ns-3-dev'.  The following three files show changes:

+++ b/src/internet/helper/ipv4-routing-helper.cc
+++ b/src/internet/helper/ipv4-routing-helper.h
+++ b/src/internet/model/ipv4-routing-protocol.h

**Comment by JudeNiroshan** [comment]
Reverted those mentioned files:
[https://github.com/nsnam/ns-3-dev-git/commit/3a0e64a78ec98c87d9afb9ee3b2225ea2bc47ac4](https://github.com/nsnam/ns-3-dev-git/commit/3a0e64a78ec98c87d9afb9ee3b2225ea2bc47ac4)
