### ISSUE TITLE
wifi module changes

### ISSUE THREAD

**Issue by tomhenderson** [JudeNiroshan/ns-3-dev-git#8]
I did not understand the need for changes to the wifi module; e.g.:

diff --git a/src/wifi/model/txop.cc b/src/wifi/model/txop.cc
index 73c32a097..9b03f9e86 100644
--- a/src/wifi/model/txop.cc
+++ b/src/wifi/model/txop.cc
@@ -748,7 +748,7 @@ Txop::SendCfFrame (WifiMacType frameType, Mac48Address addr)
     }
   else if ((m_queue->GetNPacketsByAddress (addr) > 0) && (frameType != WIFI_MAC_CTL_END)) //if no packet for that dest, send to another dest?
     {
-      Ptr<WifiMacQueueItem> item = m_queue->DequeueByAddress (addr);
+      Ptr<WifiMacQueueItem> item = m_queue->DequeueByAddress (WifiMacHeader::ADDR1, addr);

It affects the following files:

+++ b/src/wifi/model/mac-low.cc
+++ b/src/wifi/model/qos-txop.cc
+++ b/src/wifi/model/txop.cc
+++ b/src/wifi/model/wifi-mac-queue.cc
+++ b/src/wifi/model/wifi-mac-queue.h
+++ b/src/wifi/test/wifi-aggregation-test.cc

Are these needed for trust-routing, or should they be reverted?

**Comment by TommyPec** [comment]
This is a git artifact. As a matter of fact, Jude's code is in line with ns-3-dev.
I am still not very fluent with git, but I think that "origin/ns-3-dev" is 1 commit behind the one Jude forked to work.
How to fix this... as I said, I'm not fluent with git. Any suggestion is welcome.

**Comment by tomhenderson** [comment]
I will look into it and make a suggestion to Jude.
