### ISSUE TITLE
comments on aodv-trust-entry.{cc,h}

### ISSUE THREAD

**Issue by tomhenderson** [JudeNiroshan/ns-3-dev-git#9]
1) do not use the 'this' pointer to refer to private data members; e.g.:

 
 uint16_t AodvTrustEntry::GetHello () const
 {
-  return this->hello;
+  return hello;
 }

2) private data member variable names should be prefixed by 'm_' as in 'm_hello'

3) avoid some abbreviations when there are not many characters being saved.

void SetErr (uint16_t err;  -> SetError(uint16_t error)
rply -> reply
GetRply->GetReply
SetRply->SetReply
err -> error
etc.

**Comment by JudeNiroshan** [comment]
modified accordingly:
[https://github.com/JudeNiroshan/ns-3-dev-git/commit/4b642ce044f1f10725540f9810bf3b6ba8a3bf41](https://github.com/JudeNiroshan/ns-3-dev-git/commit/4b642ce044f1f10725540f9810bf3b6ba8a3bf41)
